actions: uploader: Update base image and use selenium from repo
The Chrome version on debian:buster is now too old for the latest selenium
release from pip. It turns out that debian bookworm has a Python Selenium
package in the repos, so we can just use that instead of installing from
pip (and worrying about future breakages like this, or having to pin the
pip package version).

This fixes the following error we were getting in Github Actions [1]:

    The chromedriver version (90.0.4430.212) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (118.0.5993.70); currently, chromedriver 118.0.5993.70 is recommended for chrome 118.*, so it is advised to delete the driver in PATH and retry
    Submitting /github/workspace/dist/system-monitor-next@paradoxxx.zero.gmail.com.zip as ***
    Traceback (most recent call last):
      File "/app/upload.py", line 62, in <module>
        main(username, password, zipball_path)
      File "/app/upload.py", line 28, in main
        driver = MyDriver()
      File "/app/upload.py", line 18, in __init__
        super().__init__(options=options)
      File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 50, in __init__
        keep_alive,
      File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chromium/webdriver.py", line 64, in __init__
        options=options,
      File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
        self.start_session(capabilities)
      File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
        response = self.execute(Command.NEW_SESSION, caps)["value"]
      File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
        self.error_handler.check_response(response)
      File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 90
    Current browser version is 118.0.5993.70 with binary path /github/home/.cache/selenium/chrome/linux64/118.0.5993.70/chrome

[1] https://github.com/mgalgs/gnome-shell-system-monitor-applet/actions/runs/6570053702/job/17846892728